---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: url related packages...
  become: yes
  become_user: root
  with_items:
    - traceroute
    - curl
    - wget
    - iproute
    - '{{nettools_addl_pkgs | default([])}}'
  package:
    name: '{{item}}'
    state: present
